In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# Load dataset
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)

# Calculate Variance for each feature
variances = df.var()

print("Feature Variances:")
print(variances)
print("\nFeature with highest variance:", variances.idxmax())
print("Feature with lowest variance:", variances.idxmin())

Feature Variances:
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

Feature with highest variance: petal length (cm)
Feature with lowest variance: sepal width (cm)


In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import pandas as pd
from sklearn.datasets import load_iris

# Load and Scale
data = load_iris()
X = data.data

# 1. Standardization is MANDATORY
X_scaled = StandardScaler().fit_transform(X)

# 2. Fit PCA
pca = PCA()
pca.fit(X_scaled)

print(f"Original shape: {X.shape}")
print(f"Number of components found: {pca.n_components_}")
print("\nPrincipal Components (Eigenvectors):\n", pca.components_)

Original shape: (150, 4)
Number of components found: 4

Principal Components (Eigenvectors):
 [[ 0.52106591 -0.26934744  0.5804131   0.56485654]
 [ 0.37741762  0.92329566  0.02449161  0.06694199]
 [ 0.71956635 -0.24438178 -0.14212637 -0.63427274]
 [-0.26128628  0.12350962  0.80144925 -0.52359713]]


In [3]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
import numpy as np

# Setup
X = load_iris().data
X_scaled = StandardScaler().fit_transform(X)

# Fit PCA
pca = PCA()
pca.fit(X_scaled)

# Ratios
ratios = pca.explained_variance_ratio_
cumulative = np.cumsum(ratios)

print("Variance explained by each component:")
for i, r in enumerate(ratios):
    print(f"PC{i+1}: {r:.4f} ({r*100:.1f}%)")

print("\nCumulative Variance:")
print(cumulative)
print(f"\nFirst 2 components capture {cumulative[1]*100:.1f}% of the data!")

Variance explained by each component:
PC1: 0.7296 (73.0%)
PC2: 0.2285 (22.9%)
PC3: 0.0367 (3.7%)
PC4: 0.0052 (0.5%)

Cumulative Variance:
[0.72962445 0.95813207 0.99482129 1.        ]

First 2 components capture 95.8% of the data!


In [4]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
import pandas as pd

# Load
iris = load_iris()
X_scaled = StandardScaler().fit_transform(iris.data)

# Reduce to 2 Components
pca_2 = PCA(n_components=2)
X_reduced = pca_2.fit_transform(X_scaled)

print(f"Original shape: {X_scaled.shape}")
print(f"Reduced shape: {X_reduced.shape}")
print("\nFirst 5 rows of reduced data (PC1, PC2):")
print(X_reduced[:5])

# In a real notebook, you would now use:
# plt.scatter(X_reduced[:, 0], X_reduced[:, 1], c=iris.target)

Original shape: (150, 4)
Reduced shape: (150, 2)

First 5 rows of reduced data (PC1, PC2):
[[-2.26470281  0.4800266 ]
 [-2.08096115 -0.67413356]
 [-2.36422905 -0.34190802]
 [-2.29938422 -0.59739451]
 [-2.38984217  0.64683538]]
